### ISSUE TITLE
Convention nom des repos

### ISSUE THREAD

**Issue by loicbourgois** [eleves-ig2i/eleves.ig2i.org#1]
Il faudrait se mettre d'accord pour le nom des repo. 
Pour un tp/td, je propose : `${année}-${matière}-séance${numéro}`, où :
- `${année}` vaut l'année en cours en janvier ;
- `${matière}` est le diminutif figurant sur la plaquette, par exemple `poo4` ; 
- `${numéro}` est le numéro de séance : 1, 2, 3 ...

Pour un projet associé à une matière : `${année}-${matière}-projet-${nom du projet}`
Pour un des events JPO, JDN, RI, NDL5 : `${année}-${id de l'événement}-${suffixe}`
- `-${suffixe}` est optionel. Il peut être utilisé dans le cas où un événement requiert plusieurs outils

Autre : `${année}-${nom du projet}`

**Comment by sofianegargouri** [comment]
Je suis plus partant pour mettre les IDs en premier. Quand on cherche quelque chose, on s'en fout de l'année, on veut juste un historique des choses faites dans la matière

**Comment by loicbourgois** [comment]
Deux autres points : 
- faut-il ajouter le préfixe `ig2i` à chaque fois ? 
- comment gérer l'id de la promo : l4 ou le4/la2 ? 

J'ai fait un test avec un nouveau tp qu'on a aujourd'hui : `ig2i-le4-poo-2018-seance2`
- `ig2i` optionnel
- top priorité à la la promo
- puis priorité à la matière, comme proposé par @sofianegargouri 
- puis l'année
- puis séance / sujet

Pour `seance2`, c'est peut-être mieux de mettre `tp2`

**Comment by raskyld** [comment]
Moi je suis pour laisser `ig2i` pour le référencement, aprés à vous de voir.

Pour l'`id` de la promo, le4/la2 c'est bon je pense.
Sinon le format me plait bien, à voir avec les autres :D

**Comment by sofianegargouri** [comment]
Je pense pas que "seance" ou "tp" soit approprié, car certains travaux s'étalent. Je pense qu'il vaut mieux mettre un sujet en dernier, exemple:

`ig2i-la2-poo-2018-amazon`
`ig2i-la2-web-2018-pokedex`

**Comment by raskyld** [comment]
Ouais et en plus on a une vague idée du sujet

**Comment by loicbourgois** [comment]
Je ne sais pas si c'est une bonne idée. Quand un sujet s'étale sur plusieurs séances, il arrive que l'organisation change d'une séance sur l'autre (par exemple, mise en place d'héritage). Dans ce cas, la structure finale du projet sera éloignée de la structure en séance 1.
Si les commits sont bien faits, il serait facile de remonter à la version à telle question de telle séance.
Mais en réalité, je pense qu'on aura plutôt des dump de projet terminés.

Aussi, je penses qu'un étudiant voudra chercher par numéro de tp : dans ce cas il est plus simple de chercher sur les noms des dépôts, plutôt que sur les commits.

Je suis pour conserver le numéro de séance / tp.

Après on peut très bien intégrer le nom du sujet dans le nom du dépôt s'il y en a un.

**Comment by raskyld** [comment]
On peut faire une recherche sur une organisation en entière ? Sinon on peut toujours voir pour faire un systéme de mots clefs

**Comment by loicbourgois** [comment]
Tu peux faire une recherche sur les noms des repos. 
Après une recherche sur l'ensemble des commits de l'orga, je ne sais pas (je dirais plutot non).
![image](https://user-images.githubusercontent.com/11260832/36191391-2e041196-115d-11e8-86f5-b69fbf23104e.png)

**Comment by loicbourgois** [comment]
Je clos. Si jamais vous n'êtes pas d'accord avec les règles sur http://eleves-ig2i.org/, issue ou PR :)
