### ISSUE TITLE
Quel framework pour le site?

### ISSUE THREAD

**Issue by raskyld** [eleves-ig2i/eleves.ig2i.org#2]
Un framework de préférence pour le site? ou full vanilla?

Je propose Foundation Zurb, dites moi ce que vous en pensez :p

**Comment by loicbourgois** [comment]
Je partirai bien sur du full vanilla, de manière à ce que ce soit accessible au plus grand nombre.

**Comment by sofianegargouri** [comment]
[Bulma](https://bulma.io/) pour le style
Niveau JS, je pense pas qu'on ait grand chose à part des animations qu'on ferait en CSS

**Comment by raskyld** [comment]
Hmm, ouais peut être un vanilla pour l’accessibilité en effet.
Rien nous empêche de faire des tutos sur les frameworks plus tard .

Je conaissais pas Bulma, ça à l'air pas mal
